modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="shadowgrid"
version="1.0.0"
displayName="Shadow Grid"
displayURL="http://example.com/"

credits="Sanbait"
authors="Sanbait"
description='''
Adds a Grid system to the world. Locked sectors are covered in Fog and inflict damage.
'''

[[dependencies.shadowgrid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.shadowgrid]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"


