
["Nexus Core Settings"]
	#Base radius for aggro and buffs at level 1
	#Range: 1.0 ~ 100.0
	baseRadius = 10.0
	#Extra radius added per level (Radius = Base + Level * PerLevel)
	#Range: 0.0 ~ 50.0
	radiusPerLevel = 2.0
	#Health Points added per level (MaxHP = Level * HPParLevel)
	#Range: 10.0 ~ 10000.0
	hpPerLevel = 200.0
	#Upgrade costs for each level. Format: 'modid:item_id|amount'.
	#Index 0 = resource to go from Level 1 -> 2
	#Index 1 = resource to go from Level 2 -> 3, etc.
	#Healing uses the same resource (1 item = 10% Heal).
	upgradeCosts = ["minecraft:copper_ingot|1", "minecraft:iron_ingot|10", "minecraft:gold_ingot|10", "minecraft:diamond|1", "minecraft:emerald|1", "minecraft:netherite_ingot|1", "minecraft:nether_star|1", "minecraft:dragon_egg|1", "minecraft:beacon|1"]

	["Nexus Core Settings"."Lighting Settings"]
		#Enable dynamic lighting for players holding torches (Server-side real light).
		enablePlayerLights = true
		#List of items that emit light when held.
		playerLightItems = ["minecraft:torch", "minecraft:soul_torch", "minecraft:lantern", "minecraft:soul_lantern", "minecraft:jack_o_lantern", "minecraft:glowstone", "minecraft:shroomlight", "minecraft:sea_lantern", "minecraft:froglight", "minecraft:ochre_froglight", "minecraft:pearlescent_froglight", "minecraft:verdant_froglight"]

	["Nexus Core Settings"."Lux System"]
		#Define specific Lux capacities for items.
		#Format: 'modid:item_id|capacity'
		#Default capacity for tagged items if not listed here is 1000.
		itemLuxCapacities = ["minecraft:wooden_sword|100", "minecraft:stone_sword|200", "minecraft:iron_sword|500", "minecraft:golden_sword|1000", "minecraft:diamond_sword|2000", "minecraft:netherite_sword|5000", "minecraft:wooden_pickaxe|100", "minecraft:stone_pickaxe|200", "minecraft:iron_pickaxe|500", "minecraft:golden_pickaxe|1000", "minecraft:diamond_pickaxe|2000", "minecraft:netherite_pickaxe|5000"]
		#Lux generated per tick per level.
		#Range: 0 ~ 1000
		coreLuxGenerationPerLevel = 1
		#Maximum Lux stored per level.
		#Range: 100 ~ 100000
		coreLuxCapacityPerLevel = 1000

